name: Format code using Prettier
on: [push, pull_request]

jobs:
    format:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: Install Prettier
              run: npm install --global prettier
            - name: Format code
              run: npx prettier --write .
            - name: Commit changed files
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "Format code using Prettier"
